import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f0f5",
        "on-secondary-container": "#004d6a",
        "surface-variant": "#e2e2e7",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#7bd0ff",
        "tertiary": "#532800",
        "on-primary-fixed-variant": "#07497d",
        "on-tertiary-fixed": "#2f1400",
        "tertiary-fixed": "#ffdcc4",
        "inverse-surface": "#2e3034",
        "tertiary-fixed-dim": "#ffb780",
        "on-primary-fixed": "#001c37",
        "primary-fixed": "#d2e4ff",
        "background": "#f9f9fe",
        "secondary-container": "#40c2fd",
        "primary": "#00355f",
        "tertiary-container": "#743b00",
        "on-tertiary": "#ffffff",
        "primary-container": "#0f4c81",
        "on-tertiary-container": "#f9a767",
        "on-secondary-fixed-variant": "#004c69",
        "surface-container-low": "#f3f3f8",
        "surface": "#f9f9fe",
        "outline": "#727780",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e8ed",
        "on-primary": "#ffffff",
        "on-background": "#191c1f",
        "primary-fixed-dim": "#a0c9ff",
        "on-surface": "#191c1f",
        "surface-bright": "#f9f9fe",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-lowest": "#ffffff",
        "secondary": "#00668a",
        "inverse-primary": "#a0c9ff",
        "outline-variant": "#c2c7d1",
        "on-error": "#ffffff",
        "surface-container": "#ededf3",
        "on-surface-variant": "#42474f",
        "on-error-container": "#93000a",
        "on-primary-container": "#8ebdf9",
        "on-secondary-fixed": "#001e2c",
        "surface-dim": "#d9dadf",
        "secondary-fixed": "#c4e7ff",
        "surface-container-highest": "#e2e2e7",
        "on-secondary": "#ffffff",
        "surface-tint": "#2d6197",
        "accent-orange": "#f9a767"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "section-gap": "120px",
        "gutter": "32px",
        "container-max": "1280px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        sans: ["var(--font-be-vietnam)", "system-ui", "sans-serif"],
        heading: ["var(--font-plus-jakarta)", "var(--font-be-vietnam)", "sans-serif"],
        sectionTitle: ["var(--font-great-vibes)", "var(--font-be-vietnam)", "cursive", "sans-serif"],
        meaCulpa: ["MeaCulpaCustom", "var(--font-mea-culpa)", "Mea Culpa", "cursive"],
      },
    },
  },
  plugins: [],
};
export default config;
